name: app-node-sonar
on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]  

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "15.x"
      - run: yarn
      - run: yarn test
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
